name: github_repo_view
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter: 
    sdk: flutter
  oauth2: ^2.0.0
  flutter_secure_storage: ^4.2.0
  dartz: ^0.10.1-nullsafety.1
  dio: ^4.0.0
  flutter_hooks: ^0.16.0
  hooks_riverpod:
    # git:
    #   url: https://github.com/rrousselGit/river_pod.git
    #   ref: rfc-335
    #   path: packages/hooks_riverpod
  freezed_annotation: ^0.14.1 
  webview_flutter: ^2.0.4
  flash: ^1.5.1
#  auto_route: ^2.0.1
  auto_route: ^3.2.4
  material_design_icons_flutter: ^5.0.5955-rc.1


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  freezed: ^0.14.1+3
#  auto_route_generator: ^2.0.1
  auto_route_generator: ^3.2.3
  lint: ^1.5.3

  flutter_lints: ^1.0.0

dependency_overrides:
  flutter_riverpod:
    # git:
    #   url: https://github.com/rrousselGit/river_pod.git
    #   ref: rfc-335
    #   path: packages/flutter_riverpod
  
  riverpod:
    # git:
    #   url: https://github.com/rrousselGit/river_pod.git
    #   ref: rfc-335
    #   path: packages/riverpod

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
